---
- hosts: "all"
  become: "yes"
  remote_user: "vagrant"

  tasks:

  - name: "Install Ubuntu Cloud Keyring package"
    apt:
      state: "present"
      update_cache: "yes"
      name: "ubuntu-cloud-keyring"

  - name: "Add Ubuntu Cloud Archive repository"
    apt_repository:
      repo: "{{ item }}"
      state: "present"
      update_cache: "yes"
    with_items:
    - "deb http://ubuntu-cloud.archive.canonical.com/ubuntu xenial-updates/newton main"

  - name: "Install Open vSwitch"
    apt:
      state: "present"
      update_cache: "no"
      name: "{{ item }}"
    with_items:
    - "openvswitch-common"
    - "openvswitch-switch"
    - "bridge-utils"
